# Site settings
name: 奔腾年代
email: 644511346@qq.com
author: 奔腾年代
url: https://jiaozn.github.io
resume_site: http://jiaozn.github.io
github: https://github.com/jiaozn/
baseurl: "/jiaozn.github.io"
description: There's my hole,gotta fly!
meta_description: 奔腾年代博客;644511346;jiaozn博客;jiaozn
motto: “战略上藐视敌人，战术上重视敌人”
banner: There's my hole,gotta fly!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jiaozn
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : jiaozn
    #disqus :
    #    short_name : jiaozn
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light