# Site settings
name: 奔腾年代
email: 644511346@qq.com
author: jiaozn
url: https://jiaozn.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/jiaozn/
baseurl: "/jiaozn.github.io"
description: There's my hole,gotta fly!
meta_description: 奔腾年代;个人博客
motto: Er...en?motto where?-seabiscuit
banner: Banner what?!-seabiscuit

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jiaozn
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : jiaozn
    #disqus :
    #    short_name : jiaozn
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light